### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by ZJWang9928** [wljungbergh/NeuroNCAP#3]
Thank you for your excellent job!
I am wondering when the code will be released?

**Comment by wljungbergh** [comment]
Hi! Thank you for your kind words.

We are in the process of preparing the code and uploading all weights for the neural renderer. We hope to have this ready before ECCV (end of September)

**Comment by wljungbergh** [comment]
Happy to announce that the code is now released. Have a look and let us know if you have any questions!!
