### ISSUE TITLE
About checkpoint

### ISSUE THREAD

**Issue by Zbozhou** [wljungbergh/NeuroNCAP#5]
Thanks for your work. I encountered an issue when decompressing ncap_weights.tar.gz. It shows an error, like this. I wonder if there is something wrong with the ncap_weights.tar.gz file.
![image](https://github.com/user-attachments/assets/f00be0c0-fb27-4fd6-a8d9-218a1d19e103)

**Comment by wljungbergh** [comment]
I just ran the download script `scripts/download/download_neurad_weights.sh` from a clean repo clone, and it worked (on a Linux machine).

It looks like the file you have has not been fully downloaded. The tar should be roughly 12.56GB in size once downloaded. How big is the one that you have?

**Comment by Zbozhou** [comment]
Yes you are right. I solved it. Thank you for your reply.
