### ISSUE TITLE
About VAD

### ISSUE THREAD

**Issue by Zbozhou** [wljungbergh/NeuroNCAP#7]
Thank you for your excellent work. I was wondering if you have any plans to release the code for VAD.

**Comment by wljungbergh** [comment]
Hi, 

We will release it in the future but currently we don't have any concrete time plan.

**Comment by Zbozhou** [comment]
Alright, I’m looking forward to your release, and once again, thank you for your outstanding work!

**Comment by rdesc** [comment]
For reference, this is the forked VAD repo with the runner for running NeuroNCAP with VAD 
https://github.com/wljungbergh/VAD

**Comment by rdesc** [comment]
Do you mind confirming @wljungbergh whether all the code is available in your forked repo of VAD?

Looking at the [dockerfile](https://github.com/wljungbergh/VAD/blob/main/docker/Dockerfile), it doesn't seem like it's cloning  or setting up VAD

**Comment by wljungbergh** [comment]
That is indeed the (unreleased) repo we used when running VAD, but I dont know if the published code it completely up-to-date with this (ncap) repo. Note that it is not officially released yet, hence I can not guarantee that everything runs. We likeley need to update with the current interface of neuro-ncap.

However ofc try to see if it works out of the box.

PS. The repo is mounted into the docker at the correct paths, hence there is no need for setting up it during the docker image creation.

**Comment by rdesc** [comment]
Ok sounds great, thanks for the prompt reply. I'll test it out and will report back.

**Comment by rdesc** [comment]
@wljungbergh as a follow-up question, does the forked repo include the post processing collision-avoidance optimization step (same one used in UniAD) ?

**Comment by wljungbergh** [comment]
VAD does not have the post-processing as part of their method. They include "safety-guardrails" during training instead. However, we added it to have a more fair comparasion. It can be enabled with some flags, see https://github.com/wljungbergh/VAD/blob/a4fc4b59b6ab82b927cc52f66535a55b38ac8ec0/inference/server.py#L132C1-L133C1

**Comment by rdesc** [comment]
As an update, the forked (unreleased) VAD repo does **not** run out of the box with the current NeuroNCAP setup. I'm going through each bug one by one but it would be nice to have the released version out soon

**Comment by rdesc** [comment]
If anyone is curious, this is how far I've got... I haven't been able to figure out the issue here, though, looks like an inverse / transpose in one of the transformation matrices is missing somewhere 

![Image](https://github.com/user-attachments/assets/887f8233-b6ed-4b97-8f5f-f1cdde31b473)

**Comment by JesseTowne** [comment]
@rdesc Have you successfully run VAD on NeuroNCAP?

**Comment by rdesc** [comment]
@JesseTowne I have not sorry, I haven't looked at this in a while. But it seems like theres just a small remaining bug somewhere. Let me know if you figure it out!
