### ISSUE TITLE
UniAD Metrics and Post Processing

### ISSUE THREAD

**Issue by AdityaNG** [wljungbergh/NeuroNCAP#8]
Hello `neuro-ncap` team, thank you for the well documented codebase!

I had a question regarding the following UniAD results in your `README.md`:
1. Are these results with or without post-processing?
2. Could you kindly point me towards the code or documentation to run these models with the post processing enabled?

https://github.com/atonderski/neuro-ncap/blob/ecdcf284e2b7b83c537f3292a06c0adddff55811/README.md?plain=1#L42-L52

**Comment by wljungbergh** [comment]
Hi,

The results in the table refer to the original UniAD (i.e., with post-proc enabled). To disable it you'd have to add the `--disable_col_optim` flag when starting the model node. 

That means, if running using slurm, change row 61-65 in `scripts/_slurm_compose_release.sh` to 

```
python -u inference/server.py \
    --port $model_port \
    --config_path $MODEL_CFG_PATH \
    --checkpoint_path $MODEL_CHECKPOINT_PATH \
    --disable_col_optim\  # <- this disables the post-proc
    $MODEL_ARGS \
```

or similarly for row 58-62 in `scripts/_docker_compose_release.sh`

**Comment by AdityaNG** [comment]
Thank you for the prompt response!
