### ISSUE TITLE
About the dynamic objects' unsee face 

### ISSUE THREAD

**Issue by zzz5y** [wljungbergh/NeuroNCAP#9]
Hello, thank you very much for your work. I am very curious about how your work handles the invisible surfaces of dynamic objects. Is it based on a small hypernetwork?Thank you!

**Comment by atonderski** [comment]
Hi, we use a simple mirror prior (left side of car == right side of car). Of course this doesn’t help if the front or back side is invisible, so the editing is still limited for those cases.

We did some experiments with an actor hypernetwork but did not see any noticeable improvements over this simple mirroring.

**Comment by zzz5y** [comment]
> Hi, we use a simple mirror prior (left side of car == right side of car). Of course this doesn’t help if the front or back side is invisible, so the editing is still limited for those cases.
> 
> We did some experiments with an actor hypernetwork but did not see any noticeable improvements over this simple mirroring.

ok thanks for your quick reply! It does a lot of help! And sorry for my late reply!
Finally thank you for you great work!

**Comment by zzz5y** [comment]
I wonder are there any implement about this mirror prior  in the code ,can you link it? Thanks a lot !

**Comment by atonderski** [comment]
Np! It is enabled by default in neurad in neurad-studio. Look for actor_flip

**Comment by zzz5y** [comment]
> Np! It is enabled by default in neurad in neurad-studio. Look for actor_flip

Got it! Thank you for your quick reply and great work!
